# Travis CI Configuration

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run -m nose
  - pycodestyle toac/*.py
after_success:
  - coveralls
