# Travis CI Configuration

language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run -m nose
  - pycodestyle toac/*.py
after_success:
  - coveralls
